{% set name = "dask-bigquery" %}
{% set version = "2023.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d5129f93f2e96c8ea4a14f9bf1c9789b7f0d2d8e76eaddd4f26c3feb896435ca

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - dask
    - gcsfs
    - google-cloud-bigquery >=2.11.0
    - google-cloud-bigquery-storage
    - pandas
    - pyarrow

test:
  imports:
    - dask_bigquery
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/coiled/dask-bigquery
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Read/write data from/to Google BigQuery with Dask
  doc_url: https://github.com/coiled/dask-bigquery/blob/main/README.md
  dev_url: https://github.com/coiled/dask-bigquery

extra:
  recipe-maintainers:
    - ncclementi
    - jrbourbeau
    - bnaul
